import { type NextPage } from "next";
import Head from "next/head";
import Nav from "y/components/home/Nav";
import Hero from "y/components/home/Hero";
import Feature from "y/components/home/Feature";
import Started from "y/components/home/Started";
import Footer from "y/components/home/Footer";
import { useEffect } from "react";
const Home: NextPage = () => {

  return (
    <>
      <Head>
        <title>todo daily</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
      </Head>
      <div className="m-auto overflow-hidden sm:container">
        <Nav />
        <Hero />
        <Feature />
        <Started />
        <Footer />
      </div>
    </>
  );
};

export default Home;

