import { type NextPage } from "next";
import Head from "next/head";
import Nav from "y/components/home/Nav";
const Home: NextPage = () => {

  return (
    <>
      <Head>
        <title>todo daily</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="container m-auto">
        <Nav />
      </div>
    </>
  );
};

export default Home;

