import { type NextPage } from "next";
import Head from "next/head";
import Nav from "y/components/home/Nav";
const Home: NextPage = () => {

  return (
    <>
      <Head>
        <title>todo daily</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
      </Head>
      <div className="m-auto h-screen w-full sm:container">
        <Nav />
      </div>
    </>
  );
};

export default Home;

